version: "3.8"

volumes:
  samplevolume:
    name: sample-volume

networks:
  samplenetwork:
    name: sample-network

services:
  pg:
    image: postgres:14.0
    restart: on-failure
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - samplevolume:/var/lib/postgresql/data
      - ./db/scripts:/docker-entrypoint-initdb.d/
    networks:
      - samplenetwork
  sample_api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pg
    volumes:
      - ./:/app
    ports:
      - 7777:7777
    networks:
      - samplenetwork
    env_file:
      - .env
    entrypoint: ["/bin/bash", "./scripts/entrypoint.dev.sh"]
  